apiVersion: apps/v1
kind: Deployment
metadata:
  name: designsystem-deployment-prod
spec:
  replicas: 1
  selector:
    matchLabels:
      app: designsystem-selector-prod
  template:
    metadata:
      labels:
        app: designsystem-selector-prod
    spec:
      imagePullSecrets:
        - name: cerit-io-harbor-accesstoken
      securityContext:
        runAsUser: 1000
        runAsGroup: 1000
        fsGroupChangePolicy: OnRootMismatch
        runAsNonRoot: true
        seccompProfile:
          type: RuntimeDefault
      containers:
        - name: designsystem-container-prod
          image: cerit.io/design-system/design-system-showcase:latest
          imagePullPolicy: Always
          securityContext:
            runAsUser: 1000
            allowPrivilegeEscalation: false
            capabilities:
              drop:
                - ALL
          ports:
            - name: probe-port
              containerPort: 80
          resources:
            limits:
              memory: "4Gi"
              cpu: "2"
            requests:
              memory: "512Mi"
              cpu: "2"

          # startupProbe:
          #   httpGet:
          #     path: /
          #     port: probe-port
          # readinessProbe:
          #   httpGet:
          #     path: /
          #     port: probe-port
          # livenessProbe:
          #   httpGet:
          #     path: /
          #     port: probe-port
