apiVersion: v1
kind: Service
metadata:
  name: designsystem-service-prod
spec:
  type: ClusterIP
  ports:
    - name: designsystem-port-prod-default
      port: 80
      targetPort: 80
      protocol: TCP
  selector:
    app: designsystem-selector-prod
